'use client'

import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { useConfig } from '@payloadcms/ui/providers/Config'
import { AdminViewShell } from '@/admin/components/AdminViewShell'
import { useAdminToast } from '@/admin/components/AdminToastProvider'
import { usePersistentSelection } from '@/admin/hooks/usePersistentSelection'
import { formatError, isTransientError, withRetry } from '@/admin/utils/errors'
import { SiteSelector } from '@/components/SiteSelector'
import { StatusBadge } from '@/components/StatusBadge'
import { TranslationActions } from '@/components/TranslationActions'
import { applyProjectionToParams } from '@/payload/utils/projections'

type QueueStatus = 'pending' | 'in_progress' | 'completed' | 'skipped'

type LocaleCode = string

type TranslationQueueEntry = {
  id: string
  documentId: string
  collectionSlug: string
  targetLocale: LocaleCode
  sourceLocale: LocaleCode
  status: QueueStatus
  autoGenerated?: boolean
  updatedAt?: string
  updatedBy?: string
}

type QueueDoc = {
  id: string
  documentId: string
  collectionSlug: string
  targetLocale: string
  sourceLocale: string
  status: string
  autoGenerated?: boolean
  updatedAt?: string
  updatedBy?: { email?: string; id?: string } | string
}

const statusDisplay: Record<QueueStatus | 'error', { label: string; icon: string }> = {
  pending: { label: 'Pending', icon: '⏳' },
  in_progress: { label: 'In Progress', icon: '🚧' },
  completed: { label: 'Completed', icon: '✅' },
  skipped: { label: 'Skipped', icon: '⏭️' },
  error: { label: 'Error', icon: '⚠️' },
}

const fetchQueue = async (
  serverURL: string,
  siteId: string,
  options: {
    page: number
    pageSize: number
    sortField: keyof QueueDoc
    sortDirection: 'asc' | 'desc'
    targetLocale?: string
  },
): Promise<{ entries: TranslationQueueEntry[]; total?: number }> => {
  const params = applyProjectionToParams(new URLSearchParams(), {
    include: ['documentId', 'collectionSlug', 'targetLocale', 'sourceLocale', 'autoGenerated', 'updatedAt', 'updatedBy'],
    includeWorkflow: true,
  })
  params.set('limit', String(options.pageSize))
  params.set('page', String(options.page))
  params.set('depth', '1')
  params.set('fallbackLocale', 'false')
  params.set('where[site][equals]', siteId)
  params.set('where[status][not_equals]', 'completed')
  const sortPrefix = options.sortDirection === 'desc' ? '-' : ''
  params.append('sort', `${sortPrefix}${options.sortField}`)
  params.append('sort', `${sortPrefix}id`)
  if (options.targetLocale) {
    params.set('where[targetLocale][equals]', options.targetLocale)
  }

  const response = await fetch(`${serverURL}/api/translation-queue?${params.toString()}`, {
    credentials: 'include',
  })
  if (!response.ok) {
    const errorText = await response.text().catch(() => '')
    throw new Error(errorText || 'Failed to load translation queue')
  }
  const payload = (await response.json()) as { docs?: QueueDoc[]; totalDocs?: number }
  return {
    entries: (payload?.docs || [])
      .map((doc) => ({
        id: doc.id,
        documentId: doc.documentId,
        collectionSlug: doc.collectionSlug,
        targetLocale: doc.targetLocale as LocaleCode,
        sourceLocale: doc.sourceLocale as LocaleCode,
        status: (doc.status || 'pending') as QueueStatus,
        autoGenerated: doc.autoGenerated,
        updatedAt: doc.updatedAt,
        updatedBy: typeof doc.updatedBy === 'string' ? doc.updatedBy : doc.updatedBy?.email || doc.updatedBy?.id,
      }))
      .filter((entry: TranslationQueueEntry) => entry.status !== 'skipped')
      .filter((entry: TranslationQueueEntry) => entry.autoGenerated !== false),
    total: payload?.totalDocs,
  }
}

export const TranslationQueue: React.FC = () => {
  const { config } = useConfig()
  const serverURL = config.serverURL ?? ''
  const { pushToast } = useAdminToast()
  const localeOptions = useMemo(
    () => (config.localization && 'locales' in config.localization ? config.localization.locales : []),
    [config.localization],
  )
  const [siteId, setSiteId] = usePersistentSelection<string>({ storageKey: 'admin.site', queryParam: 'site' })
  const [targetLocaleFilter, setTargetLocaleFilter, { ready: localeReady }] = usePersistentSelection<string>({
    storageKey: 'admin.locale',
    queryParam: 'lang',
  })
  const [workflowTab, setWorkflowTab] = usePersistentSelection<'approval' | 'translation' | 'all'>({
    storageKey: 'admin.workflowTab',
    queryParam: 'workflowTab',
    defaultValue: 'translation',
  })
  const [entries, setEntries] = useState<TranslationQueueEntry[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [optimistic, setOptimistic] = useState<Record<string, 'pending' | 'error'>>({})
  const [sort, setSort] = useState<{ field: keyof QueueDoc; direction: 'asc' | 'desc' }>(() => {
    if (typeof window === 'undefined') return { field: 'targetLocale', direction: 'asc' }
    try {
      const stored = window.localStorage.getItem('admin.translation.sort')
      if (stored) return JSON.parse(stored) as { field: keyof QueueDoc; direction: 'asc' | 'desc' }
    } catch {
      // ignore
    }
    return { field: 'targetLocale', direction: 'asc' }
  })
  const [page, setPage] = useState(1)
  const pageSize = 20
  const [total, setTotal] = useState<number | undefined>(undefined)

  useEffect(() => {
    try {
      window.localStorage.setItem('admin.translation.sort', JSON.stringify(sort))
    } catch {
      // ignore persistence errors
    }
  }, [sort])

  const renderLocaleBadge = useCallback(
    (locale: LocaleCode) => {
      const matching = localeOptions.find((l) => l.code === locale)
      const label = typeof matching?.label === 'string' ? matching.label : locale
      return (
        <span
          style={{
            display: 'inline-block',
            padding: '0.1rem 0.55rem',
            borderRadius: '0.65rem',
            background: 'rgba(255,255,255,0.08)',
            border: '1px solid rgba(255,255,255,0.15)',
            fontSize: '0.85rem',
          }}
        >
          {label}
        </span>
      )
    },
    [localeOptions],
  )

  const toggleSort = (field: keyof QueueDoc) => {
    setSort((prev) => ({
      field,
      direction: prev.field === field && prev.direction === 'asc' ? 'desc' : 'asc',
    }))
    setPage(1)
  }

  const loadQueue = useCallback(async () => {
    if (!siteId || !localeReady) {
      setEntries([])
      return
    }

    setLoading(true)
    setError(null)

    try {
      const { entries: next, total: totalDocs } = await withRetry(
        () =>
          fetchQueue(serverURL, siteId, {
            page,
            pageSize,
            sortField: sort.field,
            sortDirection: sort.direction,
            targetLocale: targetLocaleFilter,
          }),
        { retries: 2, delayMs: 350 },
      )
      setEntries(next)
      setOptimistic({})
      setTotal(totalDocs)
    } catch (err) {
      const formatted =
        'message' in (err as Record<string, unknown>) ? await formatError(err as Error) : { message: 'Unable to load translation queue right now.' }
      console.error('Failed to load translation queue', err)
      setError(formatted.message)
      pushToast({
        tone: isTransientError((formatted as { status?: number }).status) ? 'info' : 'error',
        title: 'Translation queue failed',
        description: formatted.message,
      })
      setEntries([])
    } finally {
      setLoading(false)
    }
  }, [localeReady, page, pageSize, pushToast, serverURL, siteId, sort.direction, sort.field, targetLocaleFilter])

  useEffect(() => {
    void loadQueue()
  }, [loadQueue])

  return (
    <AdminViewShell name="Translation Queue">
      <div style={{ padding: '2rem', color: '#f4f8ff' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h1>Translation Queue</h1>
            <p style={{ opacity: 0.7 }}>
              Track which locales still need content and mark translations as complete.
            </p>
            <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.4rem' }}>
              {(['approval', 'translation', 'all'] as const).map((tab) => (
                <button
                  key={tab}
                  className="btn btn--secondary"
                  aria-pressed={workflowTab === tab}
                  onClick={() => setWorkflowTab(tab)}
                  style={{
                    opacity: workflowTab === tab ? 1 : 0.7,
                    border:
                      workflowTab === tab ? '1px solid rgba(255,255,255,0.6)' : '1px solid rgba(255,255,255,0.25)',
                  }}
                >
                  {tab === 'approval' ? 'Approval' : tab === 'translation' ? 'Translation' : 'All'}
                </button>
              ))}
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
            <div style={{ minWidth: '12rem' }}>
              <label style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                <span style={{ fontSize: '0.85rem', opacity: 0.8 }}>Target language</span>
                <select
                  aria-label="Filter by target language"
                  value={targetLocaleFilter || ''}
                  onChange={(event) => {
                    setTargetLocaleFilter(event.target.value || undefined)
                    setPage(1)
                  }}
                  style={{
                    padding: '0.4rem 0.6rem',
                    borderRadius: '0.5rem',
                    border: '1px solid rgba(255,255,255,0.16)',
                    background: '#0b1f33',
                    color: '#f4f8ff',
                  }}
                >
                  <option value="">All</option>
                  {localeOptions.map((locale) => (
                    <option key={locale.code} value={locale.code}>
                      {typeof locale.label === 'string' ? locale.label : String(locale.code)}
                    </option>
                  ))}
                </select>
              </label>
            </div>
            <div style={{ minWidth: '12rem' }}>
              <SiteSelector value={siteId} onChange={setSiteId} />
            </div>
          </div>
        </div>

        {!siteId && !loading && (
          <p style={{ marginTop: '1.5rem', opacity: 0.8 }}>Select a site to view translations.</p>
        )}

        {error && (
          <div
            style={{
              marginTop: '1.25rem',
              padding: '0.75rem 1rem',
              borderRadius: '0.75rem',
              background: 'rgba(239, 83, 80, 0.15)',
              border: '1px solid rgba(239, 83, 80, 0.35)',
            }}
          >
            <p style={{ margin: 0, color: '#ffb4b4' }}>{error}</p>
          </div>
        )}

        {loading && siteId && <p style={{ marginTop: '1.5rem' }}>Loading translation tasks…</p>}
        {!loading && siteId && entries.length === 0 && (
          <p style={{ marginTop: '1.5rem', opacity: 0.8 }}>No outstanding translations.</p>
        )}

        {!loading && entries.length > 0 && (
          <table style={{ width: '100%', marginTop: '2rem', borderCollapse: 'collapse' }}>
            <thead>
              <tr>
                <th style={{ textAlign: 'left', padding: '0.5rem' }}>Document</th>
                <th style={{ textAlign: 'left', padding: '0.5rem' }}>
                  <button
                    type="button"
                    onClick={() => toggleSort('sourceLocale')}
                    style={{ background: 'transparent', border: 'none', color: '#e5ecfa', cursor: 'pointer' }}
                  >
                    Source {sort.field === 'sourceLocale' ? (sort.direction === 'asc' ? '▲' : '▼') : ''}
                  </button>
                </th>
                <th style={{ textAlign: 'left', padding: '0.5rem' }}>
                  <button
                    type="button"
                    onClick={() => toggleSort('targetLocale')}
                    style={{ background: 'transparent', border: 'none', color: '#e5ecfa', cursor: 'pointer' }}
                  >
                    Target {sort.field === 'targetLocale' ? (sort.direction === 'asc' ? '▲' : '▼') : ''}
                  </button>
                </th>
                <th style={{ textAlign: 'left', padding: '0.5rem' }}>
                  <button
                    type="button"
                    onClick={() => toggleSort('status')}
                    style={{ background: 'transparent', border: 'none', color: '#e5ecfa', cursor: 'pointer' }}
                  >
                    Status {sort.field === 'status' ? (sort.direction === 'asc' ? '▲' : '▼') : ''}
                  </button>
                </th>
                <th style={{ textAlign: 'left', padding: '0.5rem' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {entries.map((entry) => (
                <tr key={entry.id}>
                  <td style={{ padding: '0.5rem' }}>
                    <div style={{ fontWeight: 600 }}>{entry.collectionSlug}</div>
                    <div style={{ fontSize: '0.8rem', opacity: 0.7 }}>ID: {entry.documentId}</div>
                    {entry.updatedBy && (
                      <div style={{ fontSize: '0.8rem', opacity: 0.7 }}>
                        Updated by {entry.updatedBy}{' '}
                        {entry.updatedAt ? `at ${new Date(entry.updatedAt).toLocaleString()}` : ''}
                      </div>
                    )}
                  </td>
                  <td style={{ padding: '0.5rem' }}>{renderLocaleBadge(entry.sourceLocale)}</td>
                  <td style={{ padding: '0.5rem' }}>{renderLocaleBadge(entry.targetLocale)}</td>
                  <td style={{ padding: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    <span aria-hidden>{statusDisplay[entry.status]?.icon ?? statusDisplay.error.icon}</span>
                    <StatusBadge status={entry.status} />
                    {optimistic[entry.id] === 'pending' && (
                      <span style={{ fontSize: '0.8rem', opacity: 0.7 }}>Updating…</span>
                    )}
                    {optimistic[entry.id] === 'error' && (
                      <span style={{ fontSize: '0.8rem', color: '#ffb4b4' }}>Failed</span>
                    )}
                  </td>
                  <td style={{ padding: '0.5rem' }}>
                    <TranslationActions
                      queueId={entry.id}
                      collection={entry.collectionSlug}
                      docId={entry.documentId}
                      targetLocale={entry.targetLocale}
                      sourceLocale={entry.sourceLocale}
                      siteId={siteId}
                      lastModified={entry.updatedAt}
                      lastModifiedBy={entry.updatedBy}
                      onChange={() => {
                        void loadQueue()
                      }}
                      onOptimisticState={(queueId) =>
                        setOptimistic((prev) => ({
                          ...prev,
                          [queueId]: 'pending',
                        }))
                      }
                      onOptimisticError={(queueId) =>
                        setOptimistic((prev) => ({
                          ...prev,
                          [queueId]: 'error',
                        }))
                      }
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}

        {total && total > pageSize && (
          <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', marginTop: '1rem' }}>
            <button
              className="btn btn--secondary"
              disabled={page <= 1 || loading}
              onClick={() => setPage((prev) => Math.max(1, prev - 1))}
            >
              Previous
            </button>
            <span>
              Page {page} of {Math.ceil(total / pageSize)}
            </span>
            <button
              className="btn btn--secondary"
              disabled={loading || (total ? page >= Math.ceil(total / pageSize) : false)}
              onClick={() => setPage((prev) => prev + 1)}
            >
              Next
            </button>
          </div>
        )}
      </div>
    </AdminViewShell>
  )
}

export default TranslationQueue
