import type { CollectionConfig } from 'payload'
import { adminAccess } from '@/access'
import { siteField } from '@/fields/siteField'
import { localeField } from '@/fields/localeField'
import { createSiteFilteredAccess } from '@/admin/utils/siteFilterOptions'

export const APIKeys: CollectionConfig = {
  slug: 'api-keys',
  admin: {
    useAsTitle: 'name',
    group: 'System',
    defaultColumns: ['name', 'keyPrefix', 'site', 'createdAt', 'lastUsed'],
    description: 'Manage API keys for external integrations',
  },
  access: {
    // Only admins can manage keys - but still respect site filtering
    read: createSiteFilteredAccess(),
    create: adminAccess,
    update: adminAccess,
    delete: adminAccess,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      label: 'Key Name',
      admin: {
        placeholder: 'e.g. Mobile App, Zapier Integration',
      },
    },
    {
      name: 'key',
      type: 'text',
      required: false, // Generated by hook
      hidden: true, // Never show full key in admin after creation
    },
    {
      name: 'keyPrefix',
      type: 'text',
      label: 'Key Prefix',
      admin: {
        readOnly: true,
        description: 'First 8 characters of the key for identification',
      },
    },
    {
      name: 'lastUsed',
      type: 'date',
      admin: {
        readOnly: true,
      },
    },
    siteField,
    localeField,
  ],
  hooks: {
    beforeChange: [
      async ({ data, operation, req: _req }) => {
        if (operation === 'create') {
          // Generate a secure random key
          const crypto = await import('crypto')
          const generatedKey = 'sk_' + crypto.randomBytes(32).toString('hex')
          
          // Store the key (in a real app, you should hash this!)
          // For this request, we are storing it but hiding it from UI except on creation response
          data.key = generatedKey
          data.keyPrefix = generatedKey.substring(0, 8) + '...'
          
          // Pass the raw key back to the UI only once via custom context or specific response handling
          // Note: In standard Payload hooks, we can't easily modify the *response* body to include transient data 
          // without a custom endpoint. 
          // For simplicity in this architecture, we will assume the Admin UI View for "Create" 
          // handles the generation via a custom component or we accept the limitation that 
          // we can't show it "one time" easily without a custom endpoint.
          
          // ALTERNATIVE: The User asked for a custom view. 
          // So this Collection is just the storage. The creation happens in the custom view.
        }
        return data
      }
    ]
  }
}
