import type { CollectionConfig, Field } from 'payload'
import { adminAccess, createAccess, updateAccess } from '@/access'
import { localeField } from '@/fields/localeField'
import { siteField } from '@/fields/siteField'
import { processTranslationQueueAction } from '@/hooks/translationQueueActions'
import { createSiteFilteredAccess } from '@/admin/utils/siteFilterOptions'

export const TranslationQueue: CollectionConfig<'translation-queue'> = {
  slug: 'translation-queue',
  admin: {
    useAsTitle: 'documentId',
    description: 'Tracks localization tasks per document and locale.',
    defaultColumns: ['collectionSlug', 'documentId', 'targetLocale', 'status', 'updatedAt'],
  },
  access: {
    read: createSiteFilteredAccess(),
    create: createAccess,
    update: updateAccess,
    delete: adminAccess,
  },
  hooks: {
    beforeValidate: [
      ({ data }) => {
        if (data && !data.locale && typeof data.targetLocale === 'string') {
          data.locale = data.targetLocale
        }
        return data
      },
    ],
    afterChange: [processTranslationQueueAction],
  },
  fields: [
    {
      name: 'documentId',
      type: 'text',
      required: true,
      index: true,
    },
    {
      name: 'collectionSlug',
      type: 'text',
      required: true,
      index: true,
    },
    siteField,
    localeField,
    {
      name: 'sourceLocale',
      type: 'text',
      required: true,
    },
    {
      name: 'targetLocale',
      type: 'text',
      required: true,
      index: true,
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'pending',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'In Progress', value: 'in_progress' },
        { label: 'Completed', value: 'completed' },
        { label: 'Skipped', value: 'skipped' },
      ],
    },
    {
      name: 'autoGenerated',
      type: 'checkbox',
      label: 'Auto Generated',
      defaultValue: true,
    },
    {
      name: 'assignedTo',
      type: 'relationship',
      relationTo: 'users',
    },
    {
      name: 'notes',
      type: 'textarea',
    },
    {
      name: 'completedAt',
      type: 'date',
      admin: {
        date: {
          pickerAppearance: 'dayAndTime',
        },
      },
    },
  ] satisfies Field[],
} satisfies CollectionConfig<'translation-queue'>
