import type {
  CollectionAfterChangeHook,
  CollectionAfterReadHook,
  CollectionConfig,
  PayloadRequest,
} from 'payload'
import { cacheInvalidatePattern } from '@/payload/utils/cache'
import type { TranslationQueue as TranslationQueueDoc } from '@/payload-types'
import type { WorkflowRequest } from '@/types/PayloadRequestExtended'
import { detectMissingLocales } from '@/utils/translation'

const QUEUE_COLLECTION = 'translation-queue'

type QueueEntry = TranslationQueueDoc

type QueueWhere = {
  documentId: string
  collectionSlug: string
  targetLocale: string
  siteId: string
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null

const shouldSkipTranslationSync = (req: WorkflowRequest): boolean =>
  Boolean(req.context?.skipTranslationSync)

const resolveActiveLocale = (req: PayloadRequest, fallback = 'en'): string => {
  if (typeof req?.locale === 'string' && req.locale.length > 0) {
    return req.locale
  }

  const localizationConfig = req?.payload?.config?.localization
  if (localizationConfig && typeof localizationConfig === 'object') {
    return localizationConfig.defaultLocale
  }

  return fallback
}

const resolveSiteId = (input: unknown): string | null => {
  if (typeof input === 'string') {
    return input
  }
  if (isRecord(input) && typeof input.id === 'string') {
    return input.id
  }
  return null
}

const getCollectionConfig = (
  req: WorkflowRequest,
  collectionSlug: string,
): CollectionConfig | undefined =>
  req.payload.config.collections?.find((entry) => entry.slug === collectionSlug)

const fetchLocaleDoc = async (
  req: WorkflowRequest,
  collectionSlug: string,
  documentId: string,
  locale: string,
): Promise<Record<string, unknown> | null> => {
  try {
    const localizedDoc = await req.payload.findByID({
      collection: collectionSlug as never,
      id: documentId,
      locale: locale as never,
      depth: 0,
    })

    return localizedDoc as Record<string, unknown>
  } catch (error) {
    console.error('Unable to load localized document', { collectionSlug, documentId, locale, error })
    return null
  }
}

const loadQueueEntriesByLocale = async (
  req: WorkflowRequest,
  where: { documentId: string; collectionSlug: string; siteId: string },
): Promise<{ byLocale: Map<string, QueueEntry>; duplicates: string[] }> => {
  const results = await req.payload.find({
    collection: QUEUE_COLLECTION,
    where: {
      documentId: { equals: where.documentId },
      collectionSlug: { equals: where.collectionSlug },
      site: { equals: where.siteId },
    },
    depth: 0,
    limit: 200,
  })

  const byLocale = new Map<string, QueueEntry>()
  const duplicates: string[] = []

  for (const entry of results.docs as QueueEntry[]) {
    if (byLocale.has(entry.targetLocale)) {
      duplicates.push(String(entry.id))
      continue
    }
    byLocale.set(entry.targetLocale, entry)
  }

  return { byLocale, duplicates }
}

const deleteQueueEntry = async (req: WorkflowRequest, entryId: string): Promise<void> => {
  try {
    await req.payload.delete({
      collection: QUEUE_COLLECTION,
      id: entryId,
    })
  } catch (error) {
    console.error('Failed to delete translation queue entry', { entryId, error })
  }
}

const ensurePendingEntry = async (
  req: WorkflowRequest,
  where: QueueWhere & { sourceLocale: string },
  existingEntry?: QueueEntry,
): Promise<void> => {
  if (existingEntry) {
    if (existingEntry.status === 'completed') {
      await req.payload.update({
        collection: QUEUE_COLLECTION,
        id: existingEntry.id,
        data: { status: 'pending', autoGenerated: true },
        depth: 0,
      })
    }
    return
  }

  await req.payload.create({
    collection: QUEUE_COLLECTION,
    data: {
      documentId: where.documentId,
      collectionSlug: where.collectionSlug,
      site: where.siteId as never,
      locale: where.sourceLocale,
      sourceLocale: where.sourceLocale,
      targetLocale: where.targetLocale,
      status: 'pending',
      autoGenerated: true,
    },
    depth: 0,
    draft: false,
  })
}

const runSync = async ({
  doc,
  req,
  collectionSlug,
  locale,
}: {
  doc: Record<string, unknown>
  req: WorkflowRequest
  collectionSlug: string
  locale: string
}) => {
  const metaSource = (req as WorkflowRequest & { meta?: Record<string, unknown> }).meta?.source
  if (metaSource === 'n8n') {
    return doc
  }
  if (!doc?.id || shouldSkipTranslationSync(req)) {
    return doc
  }

  const localizationConfig = req.payload.config.localization
  const locales =
    localizationConfig && typeof localizationConfig === 'object' && 'locales' in localizationConfig
      ? (localizationConfig as { locales: { code: string }[] }).locales.map(({ code }) => code)
      : []
  if (locales.length <= 1) {
    return doc
  }

  const collectionConfig = getCollectionConfig(req, collectionSlug)
  if (!collectionConfig) {
    return doc
  }

  const documentId = String(doc.id)
  const siteId = resolveSiteId((doc as Record<string, unknown>).site)
  if (!siteId) {
    return doc
  }

  const localizedDocs: Record<string, Record<string, unknown>> = {
    [locale]: doc as Record<string, unknown>,
  }

  await Promise.all(
    locales
      .filter((code) => code !== locale)
      .map(async (code) => {
        const localized = await fetchLocaleDoc(req, collectionSlug, documentId, code)
        if (localized) {
          localizedDocs[code] = localized
        }
      }),
  )

  const missingLocales = detectMissingLocales(localizedDocs, collectionConfig, locales).filter(
    (code) => code !== locale,
  )

  const { byLocale, duplicates } = await loadQueueEntriesByLocale(req, {
    documentId,
    collectionSlug,
    siteId,
  })

  for (const duplicateId of duplicates) {
    await deleteQueueEntry(req, duplicateId)
  }

  for (const [targetLocale, entry] of byLocale.entries()) {
    if (!missingLocales.includes(targetLocale)) {
      await deleteQueueEntry(req, String(entry.id))
    }
  }

  for (const targetLocale of missingLocales) {
    await ensurePendingEntry(
      req,
      {
        documentId,
        collectionSlug,
        sourceLocale: locale,
        targetLocale,
        siteId,
      },
      byLocale.get(targetLocale),
    )
  }

  if (siteId) {
    void cacheInvalidatePattern(`site:${siteId}`).catch((error) =>
      console.error('Failed to invalidate caches after translation sync', error),
    )
  }

  return doc
}

export const syncTranslationsAfterChange: CollectionAfterChangeHook = async ({
  doc,
  req,
  collection,
}): Promise<Record<string, unknown>> => {
  const activeLocale = resolveActiveLocale(req)
  return runSync({
    doc: doc as Record<string, unknown>,
    req: req as WorkflowRequest,
    collectionSlug: collection.slug,
    locale: activeLocale,
  })
}

export const syncTranslationsAfterRead: CollectionAfterReadHook = async ({
  doc,
  req,
  collection,
}): Promise<Record<string, unknown>> => {
  const activeLocale = resolveActiveLocale(req)
  return runSync({
    doc: doc as Record<string, unknown>,
    req: req as WorkflowRequest,
    collectionSlug: collection.slug,
    locale: activeLocale,
  })
}
