#!/usr/bin/env node
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(new URL('../..', import.meta.url).pathname)
const proof = readFileSync(resolve(root, 'scripts/w2-02-local-proof.sh'), 'utf8')
const rehearsal = readFileSync(resolve(root, 'deploy/scripts/rehearse-local-restore.mjs'), 'utf8')
execFileSync('bash', ['-n', resolve(root, 'scripts/w2-02-local-proof.sh')])
execFileSync(process.execPath, ['--check', resolve(root, 'deploy/scripts/rehearse-local-restore.mjs')])
assert.match(proof, /recovery-phases\.jsonl/)
assert.match(proof, /run_phase real-service/)
assert.match(proof, /run_phase posthook/)
assert.match(proof, /run_phase payload-seed/)
assert.match(proof, /run_phase web-build/)
assert.match(proof, /local_db_scheme="postgresql:"/)
assert.match(proof, /local_db_port="54322"/)
assert.match(proof, /W2-02 local proof must use the disposable Supabase URI/)
assert.equal((proof.match(/\$\{payload_api_key_env\}=\$api_key/g) ?? []).length, 2, 'web consumers must use the generated seed API key')
assert.equal((proof.match(/\$\{w2_payload_api_key_env\}=\$api_key/g) ?? []).length, 1, 'orchestrator must use the generated seed API key')
assert.match(proof, /local_proof_api_key_env='LINKSITES_LOCAL_PROOF_API_KEY'/, 'recovery hook must name the API-key handoff variable')
assert.match(proof, /"\$\{local_proof_api_key_env\}=\$api_key"/, 'recovery hook must use the generated seed API key')
const syntheticApiKeyAssignment = ['LINKSITES_LOCAL_PROOF_', 'API_KEY', '=\"ltfx.'].join('')
assert.equal(proof.includes(syntheticApiKeyAssignment), false, 'recovery hook must not use a synthetic API key')
assert.match(proof, /local_proof_preview_token_env='LINKSITES_LOCAL_PROOF_PREVIEW_TOKEN'/, 'recovery hook must name the preview-token handoff variable')
assert.match(proof, /"\$\{local_proof_preview_token_env\}=\$preview_token"/, 'recovery hook must use the generated preview token')
assert.ok(rehearsal.includes('web_payload_api_key_env=PAYLOAD_API_KEY'), 'restarted web must name the Payload API-key handoff variable')
assert.ok(rehearsal.includes('web_preview_token_env=PREVIEW_ACCESS_TOKEN'), 'restarted web must name the preview-token handoff variable')
assert.ok(rehearsal.includes(['web_payload_api_key_env}', '=$LINKSITES_LOCAL_PROOF_API_KEY'].join('')), 'restarted web must use the runtime Payload API key')
assert.ok(rehearsal.includes(['web_preview_token_env}', '=$LINKSITES_LOCAL_PROOF_PREVIEW_TOKEN'].join('')), 'restarted web must use the runtime preview token')
assert.equal((proof.match(/\$\{preview_access_token_env\}=\$preview_token/g) ?? []).length, 2, 'web consumers must use the generated preview token')
assert.equal((proof.match(/\$\{w2_preview_access_token_env\}=\$preview_token/g) ?? []).length, 1, 'orchestrator must use the generated preview token')
assert.ok(proof.indexOf('api_key="$(node') < proof.indexOf('${payload_api_key_env}=$api_key'), 'generated API key must be read before any consumer starts')
assert.match(proof, /diagnostic_root\/cms\.log/)
assert.match(proof, /diagnostic_root\/web\.log/)
assert.match(proof, /sanitize_file/)
assert.match(proof, /\.cms\.log\.raw/)
assert.match(proof, /\.web\.log\.raw/)
assert.match(rehearsal, /recovery-failure\.json/)
assert.match(rehearsal, /w2-07-recovery-failure\.json/)
assert.match(rehearsal, /w2-02\.stderr\.log/)
assert.match(rehearsal, /api\/pages\?site=\$LINKSITES_LOCAL_PROOF_SITE_ID&limit=100/)
assert.doesNotMatch(rehearsal, /where\[status\]\[equals\]=published/)
assert.doesNotMatch(rehearsal, /promotionRunMarker\]\[equals\]=\$LINKSITES_LOCAL_PROOF_RUN_MARKER/)
assert.match(rehearsal, /filter\(\(doc\) => doc && doc\.promotionRunMarker === marker\)/)
assert.match(rehearsal, /payload-readback-summary\.json/)
assert.match(rehearsal, /totalDocs: all\.length/)
assert.match(rehearsal, /previewEnvironment: doc\?\.previewEnvironment/)
assert.match(rehearsal, /docs\.length !== 5/)
assert.match(rehearsal, /new Set\(docs\.map\(\(doc\) => doc\.id\)\)\.size !== 5/)
assert.match(rehearsal, /doc\.status !== \\"published\\" \\|\\| doc\._status !== \\"published\\"/)
process.stdout.write('Recovery diagnostics contract probe passed\n')
