import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { LS03_CANONICAL_COLLECTIONS } from '../src/payload/ls03/semanticContract.ts'

const slugs = Object.values(LS03_CANONICAL_COLLECTIONS)

if (new Set(slugs).size !== slugs.length) {
  throw new Error('LS-03 generated type closure found duplicate collection slugs.')
}
if (LS03_CANONICAL_COLLECTIONS.products === LS03_CANONICAL_COLLECTIONS.services) {
  throw new Error('Products and Services must remain distinct in generated closure.')
}

const target = join(dirname(fileURLToPath(import.meta.url)), '../src/generated/ls03-payload-types.ts')
const body = `/**
 * LS-03 generated Payload type closure.
 *
 * Regenerated by \`tsx scripts/generate-ls03-types.ts\` from the semantic contract.
 * Official \`payload-types.ts\` is also regenerated when a database is available
 * via \`LINKSITES_BUILD_NO_DATABASE=1 pnpm --filter @linksites/cms generate:types\`.
 */

export const LS03_GENERATED_COLLECTION_SLUGS = ${JSON.stringify(slugs, null, 2)} as const

export type Ls03GeneratedCollectionSlug = (typeof LS03_GENERATED_COLLECTION_SLUGS)[number]

export interface Ls03GeneratedProduct {
  semanticKind: 'product'
  title: string
  slug: string
  site: number | string
  locale: string
}

export interface Ls03GeneratedService {
  semanticKind: 'service'
  title: string
  slug: string
  site: number | string
  locale: string
}

export interface Ls03GeneratedConfigCollections {
  'template-adoptions': { adoptionId: string }
  'entitlement-snapshots': { snapshotId: string; planId: 'A' | 'B' | 'C' | 'L' }
  products: Ls03GeneratedProduct
  services: Ls03GeneratedService
  'results-work': { title: string }
  articles: { title: string }
  videos: { title: string }
  'faq-pages': { title: string }
  'help-articles': { title: string }
  'team-members': { name: string }
  locations: { name: string }
  'service-areas': { name: string }
  policies: { policyKind: 'privacy' | 'terms' | 'cookie' | 'other' }
  'core-settings': { contentMode: 'product' | 'service' | 'hybrid' | 'neither' }
}
`

writeFileSync(target, body)
console.log(`wrote ${target}`)
