#!/usr/bin/env bash
set -euo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
local_root="$(mktemp -d "${TMPDIR:-/tmp}/linksites-w2-02-local.XXXXXX")"
cms_port=4321; web_port=4322; cms_pid=""; web_pid=""
cleanup() { [[ -n "$web_pid" ]] && kill "$web_pid" >/dev/null 2>&1 || true; [[ -n "$cms_pid" ]] && kill "$cms_pid" >/dev/null 2>&1 || true; supabase --workdir "$local_root" stop --no-backup >/dev/null 2>&1 || true; rm -rf "$local_root"; }
trap cleanup EXIT
mkdir -p "$local_root/supabase" "$local_root/state"
sed "s/^project_id = .*/project_id = \"w2-02-local-${$}\"/" "$repo_root/supabase/config.toml" > "$local_root/supabase/config.toml"
SUPABASE_TELEMETRY_DISABLED=1 supabase --workdir "$local_root" start --exclude gotrue,realtime,storage-api,imgproxy,kong,mailpit,postgrest,postgres-meta,studio,edge-runtime,logflare,vector,supavisor >/dev/null
export DATABASE_URI="postgresql://postgres:postgres@127.0.0.1:54322/postgres" PAYLOAD_SECRET="w2-02-disposable-local-secret" PAYLOAD_PUBLIC_SERVER_URL="http://127.0.0.1:${cms_port}" LINKSITES_W2_04_LOCAL_PROOF=1 W2_04_PROOF_PATH="$local_root/seed.json"
pnpm --dir "$repo_root" --filter @linksites/cms exec tsx scripts/w2-04-seed.ts >/dev/null
api_key="$(node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1])).previewApiKey)' "$local_root/seed.json")"
site_id="$(node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1])).siteId)' "$local_root/seed.json")"
wait_for() { local url="$1"; for _ in $(seq 1 120); do if curl -fsS "$url" >/dev/null 2>&1; then return 0; fi; sleep 1; done; return 1; }
(cd "$repo_root" && pnpm --filter @linksites/cms dev --hostname 127.0.0.1 --port "$cms_port") >"$local_root/cms.log" 2>&1 & cms_pid="$!"
wait_for "http://127.0.0.1:${cms_port}/api/pages?site=${site_id}" || { cat "$local_root/cms.log" >&2; exit 1; }
env PAYLOAD_BASE_URL="http://127.0.0.1:${cms_port}" PAYLOAD_PUBLIC_SERVER_URL="http://127.0.0.1:${cms_port}" NEXT_PUBLIC_PAYLOAD_API_URL="http://127.0.0.1:${cms_port}" PAYLOAD_API_KEY="$api_key" PREVIEW_ACCESS_TOKEN="w2-02-private-proof-token" LINKSITES_W2_04_LOCAL_PROOF=1 LINKSITES_W2_04_LOCAL_PROOF_TEMPLATE_ID=marketing-smb-v1 LINKSITES_ADMITTED_TEMPLATE_SHA=1111111111111111111111111111111111111111 LINKSITES_ADMITTED_TEMPLATE_RECEIPT_JSON="$(node -e 'process.stdout.write(JSON.stringify(JSON.parse(require("fs").readFileSync(process.argv[1])).receipt))' "$local_root/seed.json")" LINKSITES_ADMITTED_TEMPLATE_EVIDENCE_JSON="$(node -e 'process.stdout.write(JSON.stringify(JSON.parse(require("fs").readFileSync(process.argv[1])).evidence))' "$local_root/seed.json")" pnpm --dir "$repo_root" --filter @linksites/web-master build >"$local_root/web-build.log" 2>&1
(cd "$repo_root" && env PAYLOAD_BASE_URL="http://127.0.0.1:${cms_port}" PAYLOAD_PUBLIC_SERVER_URL="http://127.0.0.1:${cms_port}" NEXT_PUBLIC_PAYLOAD_API_URL="http://127.0.0.1:${cms_port}" PAYLOAD_API_KEY="$api_key" PREVIEW_ACCESS_TOKEN="w2-02-private-proof-token" LINKSITES_W2_04_LOCAL_PROOF=1 LINKSITES_W2_04_LOCAL_PROOF_TEMPLATE_ID=marketing-smb-v1 LINKSITES_ADMITTED_TEMPLATE_SHA=1111111111111111111111111111111111111111 LINKSITES_ADMITTED_TEMPLATE_RECEIPT_JSON="$(node -e 'process.stdout.write(JSON.stringify(JSON.parse(require("fs").readFileSync(process.argv[1])).receipt))' "$local_root/seed.json")" LINKSITES_ADMITTED_TEMPLATE_EVIDENCE_JSON="$(node -e 'process.stdout.write(JSON.stringify(JSON.parse(require("fs").readFileSync(process.argv[1])).evidence))' "$local_root/seed.json")" pnpm --filter @linksites/web-master start --hostname 127.0.0.1 --port "$web_port") >"$local_root/web.log" 2>&1 & web_pid="$!"
wait_for "http://127.0.0.1:${web_port}/api/healthz" || { cat "$local_root/web.log" >&2; exit 1; }
W2_02_STATE_DIR="$local_root/state" W2_02_PAYLOAD_BASE_URL="http://127.0.0.1:${cms_port}" W2_02_PAYLOAD_API_KEY="$api_key" W2_02_PAYLOAD_SITE_ID="$site_id" W2_02_WEB_MASTER_BASE_URL="http://127.0.0.1:${web_port}" W2_02_PREVIEW_ACCESS_TOKEN="w2-02-private-proof-token" W2_02_CHROMIUM_EXECUTABLE="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" W2_02_ARTIFACT_PATH="$repo_root/docs/production-roadmap/evidence/w2-02/real-service-vertical-slice.json" pnpm --dir "$repo_root" --filter @linksites/program-orchestrator exec tsx scripts/real-service-vertical-slice.ts
